### ISSUE TITLE
Nested documents

### ISSUE THREAD

**Issue by edurguti** [pauljolsen/flask-and-mongo-datatables#1]
Hi, thanks for this library, having an issue rendered nested objects into the table, I have the following document in mongodb:
```
 {
    _id: ObjectId("5f632d124f48591f6c5db238"),
    id: "5f632d124f48591f6c5db236",
    device_name: "My_Device",
    ip_address: "10.1.1.101",
    violations: {
        aaa: "OK",
        aaa_correct: "na",
        creds: "OK",
        banner: "OK",
        logging: "NOT OK",
        vty_acl: "OK",
        line: "OK"
    },
    remediations: {
        logging: "no logging buffered 64000\nno logging monitor informational\nlogging buffered 64000 informational\nno logging console\nno logging monitor"
    },
    diffs: {
        logging_standard: "no logging buffered 64000\nno logging monitor informational\nlogging buffered 64000 informational\nno logging console\nno logging monitor",
        current_logging: "logging buffered 64000\nlogging monitor informational\nlogging origin-id hostname\nlogging host 10.95.237.51\nlogging host 10.195.138.51",
        correct_logging: "logging buffered 64000 informational\nno logging console\nno logging monitor\nlogging origin-id hostname\nlogging host 10.95.231.51\nlogging host 10.95.231.51"
    }
}
```
only: ip_address, device_name and id are displayed correctly, I wasn't able to figure out how to get the other dict (like I would normally without server processing)
I would get `violations['aaa']` in datatables as so:
`{data: "violations.aaa"}` 
Any help is appreciated

**Comment by pjosols** [comment]
Edit 2: Hmmm, maybe it does. Let me have a look.

Edit:  I think what you're trying to do is get for example `violations.aaa` as "OK" alone in its own table cell, but unfortunately the mongo-datatables library doesn't support that.  It creates a list of requested keys, so in this case `violations.aaa` is a requested key, and then [here](https://github.com/pauljolsen/mongo-datatables/blob/5fbbcf106d50cce74c949def430e627b206880b5/mongo_datatables/datatables.py#L103) it builds a 'projection' to give to an `aggregate` query, but I'm pretty sure the syntax with the `key.nested_key` isn't supported by the aggregate projection query.





Hi there, and thanks for the message. I cloned this repo, created a document in MongoDB with your sample data, and I get the expected result.
![image](https://user-images.githubusercontent.com/45241321/93471931-020d6e80-f8c2-11ea-84f2-345e1cda2c03.png)
I created a new collection called "mdt" with your one document, and updated the `table_view.html` template as follows:
```
{% extends "base.html" %}


{% block content %}
    {{ super() }}

    <div class="container">

        <h1>
            Contracts
        </h1>

        <table id="dt_table" class="table table-striped" style="width:100%">
            <thead>
            <tr>
                <th>id</th>
                <th>device_name</th>
                <th>ip_address</th>
                <th>violations</th>
                <th>remediations</th>
                <th>diffs</th>
            </tr>
            </thead>
        </table>


    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}

    <script>
        $(function () {
            $('#dt_table').DataTable({
                serverSide: true,
                ajax: {
                    url: '{{ url_for('api_db', collection='mdt') }}',
                    dataSrc: 'data',
                    type: 'GET',
                    data: function (args) {
                        return {
                            "args": JSON.stringify(args)
                        };
                    }
                },
                columns: [
                    {data: 'id'},
                    {data: 'device_name'},
                    {data: 'ip_address'},
                    {data: 'violations'},
                    {data: 'remediations'},
                    {data: 'diffs'}
                ]
            });

        });

    </script>

{% endblock %}
```

Hope this helps

**Comment by pjosols** [comment]
Ok, I think [this for loop](https://github.com/pauljolsen/mongo-datatables/blob/5fbbcf106d50cce74c949def430e627b206880b5/mongo_datatables/datatables.py#L188) is the problem:

If I comment it out
```
        for result in _results:
            result = dict(result)
            result["DT_RowId"] = str(result.pop('_id'))  # rename the _id and convert ObjectId to str

            # go through every val in result and try to json.dumps objects and arrays - skip this if strings are okay
            #for key, val in result.items():
            #    if type(val) in [list, dict, float]:
            #        result[key] = json.dumps(val)

            processed_results.append(result)

        return processed_results
```

I get the intended results.  

![image](https://user-images.githubusercontent.com/45241321/93475840-1869f900-f8c7-11ea-82db-b2eddcc240e1.png)

However notice what this does to the `remediations` and `diffs` keys, which used to display the entire embedded object.  They now appear as `[object Object]`.  Looks like with this simple fix you can do it one way or the other, but not both.  Hopefully this helps.  I'm pretty sure this will break the mongo-datatables Editor, though, so hopefully you don't need that.

**Comment by edurguti** [comment]
Hi, i did exactly that and it fixed the problem, thank you! I do not need
the editor at this point, just looking to move to server side. What are
your thoughts on ajax.reload every 30 seconds? I have about 6k documents.
In client mode it absolutely breaks the db server.

**Comment by pjosols** [comment]
great!  the server side approach only loads a 'page' of documents at a time, so for example the first 50 or 100. when you click 'next page' you get a new query with the next 50 or 100 (I use the DataTables scroller, which works the same way).  so as long as you haven't set your table to display all 6000 results at a time, reloading every 30 seconds (or even every second or two) should work great.

**Comment by edurguti** [comment]
Perfect, thank you for your answer, this made it super easy to move to
server side, literally one app route and boom :)
